### ISSUE TITLE
Compile Fail

### ISSUE THREAD

**Issue by dave-agilepixel** [ronanlevesque/FOX-CSS#3]
Running Latest NPM gulp sass (might be more widespread) causes the grid.scss file to fail to compile.

```
flex-basis: #{$size}%;
max-width: #{$size}%;
```

change it to

```
$val: $size * 1%;
flex-basis: $val;
max-width: $val;
```

This fixes the issue, I'm sure a pull request would be the best way to do this but I'm not setup for that at the moment :)

Thanks for making this awesome grid it's great!

**Comment by ronanlevesque** [comment]
@dave-agilepixel thanks! I forgot that newer Sass doesn't like this syntax...

It's fixed now. Also, I've taken the opportunity to update the package.json, reinstalling npm packages will be needed ;)
